In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
data_1d = np.array([1,2,3,4,5])

In [8]:
data_2d = np.array([[1,2,3],[4,5,6]])

In [6]:
data_1d.shape

(5,)

In [10]:
dt = data_2d.reshape(3,2)
dt

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
print(data_2d.ndim)      #Know the dimension

2


In [12]:
#Array Indexing and Slicing 

print(data_1d[0])

1


In [ ]:
print(data_2d[0,1])     #First Row 2nd column

2


In [ ]:
#Slicing

print(data_1d[:3])      #Upto 0 to 2

[1 2 3]


In [16]:
data_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(data_2d[:,1:])          #Get All rows and starting at 2nd column

[[2 3]
 [5 6]]


In [ ]:
#Array Operations 

a = np.array([1,2,3])
b = np.array([4,5,6])

add = a+b       # same like sub,multiply,divide
add

array([5, 7, 9])

In [ ]:
exp_a = np.exp(a)           # The exponential value of a 
exp_a

array([ 2.71828183,  7.3890561 , 20.08553692])

In [21]:
log_b = np.log(b)
log_b

array([1.38629436, 1.60943791, 1.79175947])

In [ ]:
#Broadcasting with Scalar

a= np.array([1,2,3,4])
b= 1      # It is a scalar value
#B value is extend the array of a , like ----> ([1,1,1,1])
add = a+b
add

array([2, 3, 4, 5])

In [24]:
#Array aggregation

data = np.array([[1,2,3],[7,8,9]])

In [26]:
summ = np.sum(data)
summ

np.int64(30)

In [ ]:
#Column sum 
column_sum = np.sum(data, axis=0)       #For column
column_sum

array([ 8, 10, 12])

In [ ]:
#Row sum 
row_sum = np.sum(data, axis=1)          #For row
row_sum

array([ 6, 24])

In [ ]:
row_mean = np.mean(data, axis=1)         #For mean
row_mean

array([2., 8.])